site_name: Open WebUI Docs
site_url: ""

docs_dir: docs

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  font:
    text: Inter
    code: JetBrains Mono

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.sections
    - navigation.top
    - navigation.instant
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tabs.link

  palette:
    - scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Light mode

extra_css:
  - assets/stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji
  - toc:
      permalink: true

plugins:
  - search

nav:
  - Open WebUI: index.md

  - Project:
      - Design Guidelines: brand.md
      - Mission: mission.md
      - Roadmap: roadmap.md
      - Security: security.md
      - Sponsorships: sponsorships.md
      - Team: team.md
      - License: license.md
      - FAQ: faq.md
      - Contributing: contributing.md

  - Getting Started:
      - Overview: getting-started/index.md
      - Quick Start:
          - Overview: getting-started/quick-start/index.md
          - Starting with OpenAI: getting-started/quick-start/starting-with-openai.md
          - Starting with OpenAI-Compatible: getting-started/quick-start/starting-with-openai-compatible.md
          - Starting with Ollama: getting-started/quick-start/starting-with-ollama.md
          - Starting with llama.cpp: getting-started/quick-start/starting-with-llama-cpp.md
          - Starting with vLLM: getting-started/quick-start/starting-with-vllm.md
          - Starting with Functions: getting-started/quick-start/starting-with-functions.md
          - Docker:
              - Docker Compose: getting-started/quick-start/tab-docker/DockerCompose.md
              - Docker Desktop Extension: getting-started/quick-start/tab-docker/DockerDesktopExtension.md
              - Docker Swarm: getting-started/quick-start/tab-docker/DockerSwarm.md
              - Docker Updating: getting-started/quick-start/tab-docker/DockerUpdating.md
              - Manual Docker: getting-started/quick-start/tab-docker/ManualDocker.md
              - Podman: getting-started/quick-start/tab-docker/Podman.md
              - Podman (KubePlay): getting-started/quick-start/tab-docker/PodmanKubePlay.md
              - Podman Quadlet: getting-started/quick-start/tab-docker/PodmanQuadlet.md
              - WSL: getting-started/quick-start/tab-docker/WSL.md
          - Kubernetes:
              - Helm: getting-started/quick-start/tab-kubernetes/Helm.md
          - Python:
              - Conda: getting-started/quick-start/tab-python/Conda.md
              - Venv: getting-started/quick-start/tab-python/Venv.md
              - Uv: getting-started/quick-start/tab-python/Uv.md
              - Python Updating: getting-started/quick-start/tab-python/PythonUpdating.md
      - Advanced Topics:
          - Overview: getting-started/advanced-topics/index.md
          - Development: getting-started/advanced-topics/development.md
          - HTTPS Encryption: getting-started/advanced-topics/https-encryption.md
          - Logging: getting-started/advanced-topics/logging.md
          - Network Diagrams: getting-started/advanced-topics/network-diagrams.md
          - Monitoring:
              - Overview: getting-started/advanced-topics/monitoring/index.md
              - OpenTelemetry: getting-started/advanced-topics/monitoring/otel.md
      - Environment Config: getting-started/env-configuration.md
      - API Endpoints: getting-started/api-endpoints.md
      - Updating: getting-started/updating.md

  - Features:
      - Overview: features/index.md
      - MCP: features/mcp.md
      - Memory: features/memory.md
      - Notes: features/notes.md

      - Chat Features: features/chat-features/index.md
      - Pipelines: features/pipelines/index.md
      - Plugins: features/plugin/index.md
      - RAG: features/rag/index.md
      - RBAC: features/rbac/index.md
      - Workspace: features/workspace/index.md
      - Evaluation: features/evaluation/index.md

      - Audio:
          - STT: features/audio/speech-to-text/index.md
          - TTS: features/audio/text-to-speech/index.md

      - Image Generation: features/image-generation-and-editing/usage.md

      - Web Search: features/web-search/agentic-search.md

  - Enterprise:
      - Overview: enterprise/index.md
      - Architecture: enterprise/architecture.md
      - Customization: enterprise/customization.md
      - Integration: enterprise/integration.md
      - Partners: enterprise/partners.md
      - Security: enterprise/security.md
      - Support: enterprise/support.md
      - Customers: enterprise/customers/index.md

  - Tutorials:
      - Overview: tutorials/offline-mode.md
      - Deployment: tutorials/deployment/index.md
      - HTTPS: tutorials/https/nginx.md
      - Integrations: tutorials/integrations/azure-openai/index.md
      - Maintenance: tutorials/maintenance/database.md
      - Tips: tutorials/tips/rag-tutorial.md

  - Troubleshooting:
      - Overview: troubleshooting/index.md
      - Audio: troubleshooting/audio.md
      - Connection Errors: troubleshooting/connection-error.md
      - Performance: troubleshooting/performance.md
      - Image Generation: troubleshooting/image-generation.md
      - RAG: troubleshooting/rag.md
      - SSO: troubleshooting/sso.md
      - Web Search: troubleshooting/web-search.md
